# -*- coding: utf-8 -*-
"""AI FIRST-LAB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YjDwWjNkrj0XE4Lgt0oJdnC6niL2IqQj
"""



"""Hello"""

a = 5
b = 10
sum = a + b

print("The sum is", sum)

"""subtraction"""

a = 10
b = 5
sub = a-b
print(sub)

"""division"""

a = 100
b = 50
divide = a/b

print("the division is ", divide)



"""multiplication"""

a = 60
b = 10
multiply = a*b
print("the multiplication is ", multiply)

"""# New Section"""