# -*- coding: utf-8 -*-
"""Lab2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ht1PFYNlqpWnWUoL9oMHKMbOQshUEM4K

# Task1: lists
"""

!pip install numpy

#creating a list of 10 integers
numbers = [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
print('original List', numbers)

#sum
print('sum', sum(numbers))

#maximum
print('maximum', max(numbers))

#minimum
print('minimum ', min(numbers))


#adding new element to the list
numbers.append(22)

#removing element from the list
numbers.remove(20)

#print new list
print('updated list ', numbers)

"""# Task3: sets

"""

#two set with unique elements

set_a = {1,2,3,4,5}
set_b = {4,5,6,7,8}

# uniion and intersection

print('union', set_a | set_b)
print('Intersection', set_a & set_b)
print('Differnce', set_a - set_b)

"""# Task4: dictonaries"""

# creta 5 unique Keys
students = {'Ali': 85,'Salman':90,'Rehman':30,'Yawar':40}

print('Keys', students.keys())
print('Values', students.values())

"""# Task5: numpy

# Task06: matplotlib

# Task02: tuples
"""

# Create a tuple of 5 Strings
fruits = ('apple','Banana','cherry','mango','grape')
print('Second element', fruits[1])
print('Last one', fruits[-1])

# convert tuple into list
fruits_list = list(fruits)
fruits_list[2] = 'orange'
print('Modified', fruits_list)